apiVersion: batch/v1
kind: Job
metadata:
  generateName: soaktest-
  namespace: ${NAMESPACE}
  labels:
    app: soaktest
spec:      
  completions: 1
  parallelism: 1
  backoffLimit: 2
  template:
    metadata:
      labels:
        app: soaktest
    spec:
      restartPolicy: Never
      volumes:
        - name: config
          configMap:
            name: soaktest-config
            defaultMode: 0777
        - name: soaktest-auth
          secret:
            secretName: soaktest
      containers:
        - image: ${TELEPORT_IMAGE}
          name: teleport
          envFrom:
          - configMapRef:
              name: soaktest-config
          - secretRef:
              name: soaktest
          command:
            - /bin/sh
            - -c
            - |
              cp /scripts/soaktest.sh /tmp
              chmod +x /tmp/soaktest.sh
              /tmp/soaktest.sh
          volumeMounts:
            - mountPath: /scripts
              name: config
              readOnly: true
            - mountPath: /etc/teleport
              name: soaktest-auth
              readOnly: true
