apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: tc
  name: tc
  namespace: ${NAMESPACE}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tc
  template:
    metadata:
      labels:
        app: tc
    spec:
      volumes:
        - name: config
          configMap:
            name: tc-config
        - name: license
          secret:
            secretName: license
      containers:
        - image: ${TELEPORT_IMAGE}
          args: ["-d", "--insecure", "--diag-addr=0.0.0.0:3434"]
          name: tc
          ports:
            - containerPort: 3022
              name: nodessh
              protocol: TCP
            - name: diag
              containerPort: 3434
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /healthz
              port: 3434
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 2
          livenessProbe:
            failureThreshold: 3
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: 3434
            timeoutSeconds: 1
          volumeMounts:
            - name: config
              mountPath: /etc/teleport/
              readOnly: true
            - name: license
              mountPath: /var/lib/teleport/license.pem
              subPath: license.pem
              readOnly: true
